# Generated by Django 5.2.7 on 2026-02-22 11:03

import app_home.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Подзаголовок')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Алиас')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотры')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активен')),
                ('is_checked', models.BooleanField(blank=True, default=False, verbose_name='Выбран')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_home.models.page_image_path, verbose_name='Изображение')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Иконка SVG')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Прикрепленная ссылка')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name='Количество')),
                ('seo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название для SEO')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключевики для SEO')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес точки')),
                ('drag', models.BooleanField(blank=True, default=True, verbose_name='Перетаскивание карты')),
                ('scroll', models.BooleanField(blank=True, default=True, verbose_name='Прокрутка карты')),
                ('zoom', models.IntegerField(blank=True, default=15, verbose_name='Масштаб карты')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to='app_home.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Алиас')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_home.models.page_image_path, verbose_name='Изображение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app_home.pagecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория страниц',
                'verbose_name_plural': 'Категории страниц',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_home.pagecategory', verbose_name='Категория'),
        ),
    ]
