# Generated by Django 5.2.7 on 2026-02-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('kid_name', models.CharField(max_length=100, verbose_name='Имя ребёнка')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Желаемая дата и время, вопросы')),
                ('is_agree', models.BooleanField(blank=True, default=False, verbose_name='Согласие на обработку персональных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Заявка на экскурсию',
                'verbose_name_plural': 'Заявки на экскурсию',
            },
        ),
    ]
