# Generated by Django 5.2.7 on 2026-02-21 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с 79 и содержать 11 цифр, например: 79529999999', regex='^79\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
